### ISSUE TITLE
TypeError in classification block's ClosestAssignment

### ISSUE THREAD

**Issue by PaulLerner** [pyannote/pyannote-pipeline#16]
I get a TypeError related to [this line](https://github.com/pyannote/pyannote-pipeline/blob/develop/pyannote/pipeline/blocks/classification.py#L97) where you compare distances and threshold :
`TypeError: '>' not supported between instances of 'float' and 'Uniform'`

**Comment by hbredin** [comment]
Can you please provide a sample code leading to this error?
It looks like you forgot to `Pipeline.instantiate(...)`

**Comment by PaulLerner** [comment]
> It looks like you forgot to `Pipeline.instantiate(...)`

Indeed ! 
Sorry about that :/
