### ISSUE TITLE
GPU Training 

### ISSUE THREAD

**Issue by lizolson1** [pyannote/pyannote-pipeline#31]
Is it possible to use a gpu for hyper parameter sweeping, as in the pyannote-audio speaker diarization tutorial:
`pyannote-pipeline train --subset=development --forever ${EXP_DIR} AMI.SpeakerDiarization.MixHeadset `

I see it is supported with 'pyannote-audio ${TASK} train --gpu'. I tried using a --gpu flag to the above command but was prompted with the usage instructions. Thank you.

**Comment by hbredin** [comment]
`pyannote-pipeline train` does not support GPU.

One solution to speed things up is to run multiple instances of `pyannote-pipeline train` in parallel.
