### ISSUE TITLE
Random seed setting on Optuna Sampler

### ISSUE THREAD

**Issue by gradient-ascent-ai-lab** [pyannote/pyannote-pipeline#43]
While re-running some evaluations of overlapped speech detection, I came across variations in the results. I found the variation was coming from the Optuna Sampler in the pipeline optimization step, which is instantiated without passing in a seed:

https://github.com/pyannote/pyannote-pipeline/blob/820e592e98324b7462e0409f462f81cb7422e08d/pyannote/pipeline/optimizer.py#L95

Passing in a seed makes the runs reproducible: 
`self.sampler = getattr(optuna.samplers, sampler)(seed=42)`

I see that a sampler instance can also be passed, which would allow setting the seed without modifying this library's code. However I think perhaps it would be clearer for new users to have an optional `seed` parameter in the `__init__`, or add a comment  in the docstring about instantiating your own sampler for fixed seeds / reproducible runs. Happy to create a PR for this.

Thanks for a great toolkit!

**Comment by hbredin** [comment]
Thanks for the feedback.

Yes, I'd gladly merge a PR adding a `seed` parameter in the `__init__`.

However, I'd like to keep the current default behavior when no seed is passed by the user 
I rely on this behavior when running multiple instances of the optimizer in parallel, all sharing the same trial database.

**Comment by gradient-ascent-ai-lab** [comment]
Excellent, see #44. Closing this issue, further discussion can move to the PR.
