### ISSUE TITLE
Expose n_jobs in Optimizer to use many CPUs

### ISSUE THREAD

**Issue by geniki** [pyannote/pyannote-pipeline#7]
I'd like to tune a (pyannote-audio) pipeline faster by taking advantage of a high CPU machine. `n_jobs` in `optimizer.py` is hardcoded to 1. Would exposing this flag help me achieve what I want?

Thanks

**Comment by hbredin** [comment]
I would instead recommend running multiple instances of `pyannote-pipeline train ...` at the same time. They will all share the same trial databases. This is what I do on our CPU cluster...

**Comment by geniki** [comment]
Thanks. Any reason to prefer this over exposing `n_jobs` in general? (Sorry, I'm not familiar with the underlying `optuna` library.)

**Comment by hbredin** [comment]
Mostly because of `pyannote-metrics` that might behave weirdly in a multi-threaded context.
